ERROR_EMPTY_STACK = "Ошибка: не хватает операндов."
ERROR_DIVISION_BY_ZERO = "Ошибка: деление на ноль."
ERROR_INVALID_TOKEN = "Ошибка: недопустимый токен."
ERROR_TOO_MANY_OPERANDS = "Ошибка: слишком много чисел."
ERROR_MODULO_FLOAT = "Ошибка: остаток от деления и целочисленное деление применимы только с целыми числами"
