[project]
name = "rpn-calculate"
version = "0.1.0"
description = "Программа реализует калькулятор выражений, записанных в обратной польской нотации(RPN)"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.2",
]